**Determinant**

   **Definition:**

The determinant of a square matrix $A$ is a scalar, denoted as $\det(A)$, and it determines whether the matrix is singular or nonsingular.
- If $\det(A) \neq 0$, then $A$ is invertible (nonsingular).
- If $\det(A) = 0$, then $A$ is singular (not invertible).

Determinant of a $2 \times 2$ Matrix:

   $$A = \begin{bmatrix} a & b \\ c & d \end{bmatrix}, \quad  det(A) = ad - bc.$$
  

**Properties of Determinants:**

The determinant satisfies the following axioms:
1. Adding a multiple of one row to another does not change the determinant.
2. Interchanging two rows changes the sign of the determinant.
3. Multiplying a row by a scalar multiplies the determinant by the same scalar.
4. The determinant of an upper triangular matrix is the product of its diagonal entries.

**Determinant Calculation Using Row Operations**

- Use Gaussian Elimination to transform A into an upper triangular form.
- Compute the determinant as the product of the pivots.
- If row interchanges are performed, adjust sign accordingly.

**Key Theorems**


  **Theorem: Determinant of a Product**

   $$\det(AB) = \det(A) \cdot \det(B).$$
   
  **Theorem: Determinant of an Inverse**
    $$\det(A^{-1}) = \frac{1}{\det(A)} \quad \text{if } A \text{ is invertible}.$$


In [2]:
import numpy as np

def determinant_by_row_operations(A):
    """
    Compute the determinant of a square matrix A using Gaussian elimination
    (row operations) without np.linalg.det, and print the upper triangular matrix U.
    """
    A = A.astype(float)   # Make sure entries are floats to avoid integer division
    n = A.shape[0]
    swap_count = 0        # Count how many row swaps occur

    for i in range(n):
        # --- Pivot selection ---
        # If the pivot element is zero, try to swap with a row below to get a nonzero pivot
        if A[i, i] == 0:
            for j in range(i + 1, n):
                if A[j, i] != 0:
                    A[[i, j]] = A[[j, i]]  # Swap rows i and j
                    swap_count += 1
                    break

        # If pivot is still zero, determinant is zero
        if A[i, i] == 0:
            print("Matrix is singular; determinant = 0.")
            print("Upper triangular matrix U:")
            print(A)
            return 0.0

        # --- Elimination below the pivot ---
        # Make all entries below the pivot zero
        for j in range(i + 1, n):
            factor = A[j, i] / A[i, i]
            A[j, i:] -= factor * A[i, i:]

    # At this point A has been transformed into the upper triangular matrix U
    print("Upper triangular matrix U:")
    print(A)

    # Multiply diagonal entries to get determinant
    det = np.prod(np.diag(A))

    # Adjust sign if an odd number of row swaps occurred
    if swap_count % 2 != 0:
        det = -det

    return det

# ---- Example usage ----
n = int(input("Enter matrix size (n for n×n): "))
print("Enter the matrix row by row, with spaces between numbers:")
rows = []
for i in range(n):
    row = list(map(float, input(f"Row {i+1}: ").split()))
    rows.append(row)

A = np.array(rows)
print("Matrix A:")
print(A)

detA = determinant_by_row_operations(A.copy())
print("Determinant of A =", detA)


Enter matrix size (n for n×n): 4
Enter the matrix row by row, with spaces between numbers:
Row 1: 1 0 -1 2
Row 2: 2 1 -3 4
Row 3: 0 2 -2 3
Row 4: 1 1 -4 -2
Matrix A:
[[ 1.  0. -1.  2.]
 [ 2.  1. -3.  4.]
 [ 0.  2. -2.  3.]
 [ 1.  1. -4. -2.]]
Upper triangular matrix U:
[[ 1.  0. -1.  2.]
 [ 0.  1. -1.  0.]
 [ 0.  0. -2. -4.]
 [ 0.  0.  0.  3.]]
Determinant of A = 6.0


**Conclusion**

- Determinants provide a criterion for matrix invertibility.
- Gaussian elimination is the most efficient way to compute determinants in practice.
- Determinants satisfy key algebraic properties that simplify calculations.