**Orthogonal Matrix**

 A **square matrix** $Q$ is called **orthogonal** if its rows and columns are orthogonal unit vectors, meaning that it satisfies the condition:

$$
  Q^\top Q = Q Q^\top = I
$$

  where:

- $Q^\top$  is the transpose of $Q$,
- $I$ is the identity matrix of the same size as $Q$.


**Determinant of an Orthogonal Matrix**

For an orthogonal matrix $Q$, we have:

$$
        Q^T Q = I
$$

Taking the determinant on both sides:

$$
        \det(Q^T Q) = \det(I)
$$

Using the property $\det(AB) = \det(A) \det(B)$, we get:

$$
        \det(Q^T) \det(Q) = 1
$$

Since $\det(Q^T) = \det(Q)$, it follows that:

$$
        \det(Q)^2 = 1 \Rightarrow \det(Q) = \pm 1
$$

**Orthogonality of a 2×2 Matrix**

A $2 \times 2$ matrix $Q$ is given by:
$$
        Q = \begin{bmatrix} a & b \\ c & d \end{bmatrix}
$$

It is orthogonal if and only if its columns:

$$
        u_1 = \begin{bmatrix} a \\ c \end{bmatrix}, \quad u_2 = \begin{bmatrix} b \\ d \end{bmatrix}
$$

form an orthonormal basis of $\mathbb{R}^2$, i.e.,
$$
        \langle u_1, u_2 \rangle = 0, \quad \| u_1 \| = 1, \quad \| u_2 \| = 1.
$$


This condition ensures that $Q^T Q = I$, making $Q$ an orthogonal matrix.

**QR Factorization**

Definition:

Any non-singular matrix $A$ can be factorized as:
    $A = QR$,
    
where $Q$ is an orthogonal matrix and $R$ is upper triangular.

- Useful in eigenvalue computation, least squares problems.


**Step-by-Step Algorithm**

Given matrix $A$, compute QR using:


1. Compute $r_{jj} = \sqrt{a_{1j}^2 + \dots + a_{nj}^2}$.
2. Normalize: $q_j = \frac{a_j}{r_{jj}}$.
3. Compute $r_{jk} = q_j^T a_k$ for  $k > j$
4. Update: $a_k = a_k - q_j r_{jk}$.

In [19]:
import numpy as np

# Display numbers up to 4 decimal places
np.set_printoptions(precision=4, suppress=True)

# Function to check orthogonality
def is_orthogonal(Q, tol=1e-8):
    I = np.eye(Q.shape[0])
    return np.allclose(Q.T @ Q, I, atol=tol)

# Step-by-step QR decomposition for any square matrix
def qr_step_by_step_general(A):
    n = A.shape[1]
    Q = np.zeros_like(A, dtype=float)
    R = np.zeros((n, n), dtype=float)
    
    print("Original matrix A:\n", A)
    
    for j in range(n):
        v = A[:, j].copy()
        print(f"\nStep for column {j+1}:")#Compute Column of Q andNormalize them
        
        for i in range(j):
            R[i, j] = np.dot(Q[:, i], A[:, j])
            v = v - R[i, j] * Q[:, i]
            print(f"r{i+1}{j+1} = q{i+1}^T * a{j+1} = {R[i, j]:.4f}")
            print(f"Updated vector v = a{j+1} - sum(r*q) =\n{v}")
        
        R[j, j] = np.linalg.norm(v)
        Q[:, j] = v / R[j, j]
        print(f"r{j+1}{j+1} = ||v|| = {R[j,j]:.4f}")
        print(f"Normalized q{j+1} =\n{Q[:, j]}")
    
    print("\nStep 3: Forming Q and R")
    print("Matrix Q =\n", Q)
    print("Matrix R =\n", R)
    
    # Verify A = QR
    QR = Q @ R
    print("\nStep 4: Verify A = QR")
    print("QR =\n", QR)
    print("Is A = QR? ->", np.allclose(A, QR))
    
    # Check orthogonality of Q
    print("\nCheck orthogonality of Q from QR decomposition:")
    print("Is Q orthogonal? ->", is_orthogonal(Q))
    
    # Rotation or reflection
    det_Q = np.linalg.det(Q)
    if det_Q > 0:
        print("Q represents a rotation (det(Q) = {:.4f})".format(det_Q))
    else:
        print("Q represents a reflection (det(Q) = {:.4f})".format(det_Q))
    
    return Q, R

# -----------------------------
# User input for n x n matrix
# -----------------------------
n = int(input("Enter the dimension of the square matrix: "))
print("Enter the entries of the matrix row by row (space separated):")
A = np.zeros((n, n), dtype=float)
for i in range(n):
    row = list(map(float, input(f"Row {i+1}: ").split()))
    A[i, :] = row

# Run step-by-step QR
Q, R = qr_step_by_step_general(A)


Enter the dimension of the square matrix: 2
Enter the entries of the matrix row by row (space separated):
Row 1: 1 1
Row 2: 1 -1
Original matrix A:
 [[ 1.  1.]
 [ 1. -1.]]

Step for column 1:
r11 = ||v|| = 1.4142
Normalized q1 =
[0.7071 0.7071]

Step for column 2:
r12 = q1^T * a2 = 0.0000
Updated vector v = a2 - sum(r*q) =
[ 1. -1.]
r22 = ||v|| = 1.4142
Normalized q2 =
[ 0.7071 -0.7071]

Step 3: Forming Q and R
Matrix Q =
 [[ 0.7071  0.7071]
 [ 0.7071 -0.7071]]
Matrix R =
 [[1.4142 0.    ]
 [0.     1.4142]]

Step 4: Verify A = QR
QR =
 [[ 1.  1.]
 [ 1. -1.]]
Is A = QR? -> True

Check orthogonality of Q from QR decomposition:
Is Q orthogonal? -> True
Q represents a reflection (det(Q) = -1.0000)
