**LDV Factorization**

   The LDV factorization decomposes a matrix $A$ into three matrices:


\begin{equation} A = LDV
\end{equation}
   where:

 - $L$ is a lower unitriangular matrix,
 - $D$ is a diagonal matrix with nonzero entries,
 - $V$ is an upper unitriangular matrix.
 
 Theorem:
 
 Matrix $A$ is regular if and only if it admits an LDV factorization

**Steps to Compute LDV FactorizationI**

   Given a matrix $A$:
    
- Perform Gaussian elimination to obtain an upper triangular matrix $U$.
- Extract the diagonal elements of $U$ to form the diagonal matrix $D$.
- Normalize $U$ by dividing each row by its diagonal element to get $V$.
- The matrix $L$ is formed using the multipliers used in elimination.

**Example: LDV Factorization**

   Given matrix:
     $$A = \begin{bmatrix} 2 & 1 \\ 4 & 3 \end{bmatrix}$$
    
 1- Step 1. Perform Gaussian elimination to get U:
     $$U = \begin{bmatrix} 2 & 1 \\ 0 & 1 \end{bmatrix}$$
    
 2-Step 2. Extract D:
     $$D = \begin{bmatrix} 2 & 0 \\ 0 & 1 \end{bmatrix}$$
    
 3-Step 3. Compute V:
     $$V = \begin{bmatrix} 1 & \frac{1}{2} \\ 0 & 1 \end{bmatrix}$$
    
 4-Step 4. Compute L:
     $$L = \begin{bmatrix} 1 & 0 \\ 2 & 1 \end{bmatrix}$$
    
Verify LDV Factorization: Magic!!!


In [1]:
import numpy as np

def ldv_factorization(A):
    """
    Compute the LDV factorization of a square matrix A.
    A = L * D * V
    L: lower unitriangular matrix
    D: diagonal matrix
    V: upper unitriangular matrix
    """
    A = A.astype(float)  # ensure floating point operations
    n = A.shape[0]
    
    # Step 1: Perform Gaussian elimination to obtain U
    # and collect multipliers to form L
    U = A.copy()
    L = np.eye(n)  # start L as the identity matrix
    for i in range(n - 1):
        for j in range(i + 1, n):
            if U[i, i] == 0:
                raise ValueError("Zero pivot encountered!")  # no division by zero
            m = U[j, i] / U[i, i]  # multiplier for elimination
            L[j, i] = m            # store multiplier in L
            U[j, :] -= m * U[i, :] # eliminate entry below the pivot
    
    # Step 2: Extract the diagonal matrix D from U
    D = np.zeros((n, n))
    for i in range(n):
        D[i, i] = U[i, i]
    
    # Step 3: Normalize U by dividing each row by its diagonal element to get V
    V = np.zeros((n, n))
    for i in range(n):
        V[i, :] = U[i, :] / D[i, i]
    
    return L, D, V

# ---- Take matrix from user ----
n = int(input("Enter the size of the matrix n (e.g. 3 for 3x3): "))
A = np.zeros((n, n))
print("Enter the matrix row by row:")
for i in range(n):
    row = input(f"Row {i+1} (space separated numbers): ").split()
    A[i, :] = [float(x) for x in row]

# Perform LDV factorization
L, D, V = ldv_factorization(A)

# Print results
print("\nL =")
print(L)
print("\nD =")
print(D)
print("\nV =")
print(V)

# Check by reconstructing A
A_reconstructed = L @ D @ V
print("\nReconstructed A =")
print(A_reconstructed)


Enter the size of the matrix n (e.g. 3 for 3x3): 2
Enter the matrix row by row:
Row 1 (space separated numbers): 2 1
Row 2 (space separated numbers): 4 3

L =
[[1. 0.]
 [2. 1.]]

D =
[[2. 0.]
 [0. 1.]]

V =
[[1.  0.5]
 [0.  1. ]]

Reconstructed A =
[[2. 1.]
 [4. 3.]]


**Matrix Transpose**

Definition: 

The transpose of an $m \times n$ matrix $A$ is an $n \times m$ matrix $A^T$ such that:

   \begin{equation}
        (A^T)_{ij} = A_{ji}
    \end{equation}
    
Example:
$A = \begin{bmatrix} 1 & 2 & 3 \\ 4 & 5 & 6 \end{bmatrix}, \quad A^T = \begin{bmatrix} 1 & 4 \\ 2 & 5 \\ 3 & 6 \end{bmatrix}$

**Properties:**

- $(A^T)^T = A$ (Double Transpose)
- $(A+B)^T = A^T + B^T$ (Addition)
- $(cA)^T = cA^T$ (Scalar Multiplication)
- $(AB)^T = B^T A^T$ (Product Transpose Rule)
- $A$ is symmetric if and only if $A = A^T$.


In [4]:
import numpy as np

# --- Take matrix from user ---
rows = int(input("Enter number of rows: "))
cols = int(input("Enter number of columns: "))

# Create empty array
A = np.zeros((rows, cols))

print("Enter the matrix row by row:")
for i in range(rows):
    row = input(f"Row {i+1} (space separated numbers): ").split()
    A[i, :] = [float(x) for x in row]

# --- Compute transpose ---
A_T = A.T  # or np.transpose(A)

# --- Print results ---
print("\nOriginal matrix A =")
print(A)
print("\nTranspose A^T =")
print(A_T)


Enter number of rows: 2
Enter number of columns: 3
Enter the matrix row by row:
Row 1 (space separated numbers): 1 2 3
Row 2 (space separated numbers): 4 5 6

Original matrix A =
[[1. 2. 3.]
 [4. 5. 6.]]

Transpose A^T =
[[1. 4.]
 [2. 5.]
 [3. 6.]]
