**LU Factorization and Theorem**

- The coefficient matrix A can be factored as A = LU, where:

  . L is a lower unitriangular matrix (1’s on the diagonal).
  
  . U is an upper triangular matrix with nonzero diagonal entries (pivots of A).
  
  
-  Matrix multiplication verifies the factorization:

       LU = (l1L2L3)(E3E2E1A) = A.
   
- Theorem: Matrix A is regular if and only if it can be factored as A = LU.

Matrix: 
$$A=
\begin{bmatrix}
2 & 1 & 1 \\
4 & 5 & 2 \\
2 & -2 & 0
\end{bmatrix}
$$


Steps:

1. Gaussian elimination to get U.
2. Track row operations to build L.

Result:

$$L=
\begin{bmatrix}
1 & 0 & 0 \\
2 & 1 & 0 \\
1 & -1 & 1
\end{bmatrix}
$$,

$$U=
\begin{bmatrix}
2 & 1 & 1 \\
0 & 3 & 0 \\
0 & 0 & -1
\end{bmatrix}
$$
Verify: LU = A

**Back Substitution**

Solving Ux = c:

- Start with the last equation and solve for xn.
- Substitute into previous equations to solve for xn−1, . . . , x1.

Formula:

$$x_i = \frac{1}{u_{ii}} \left(c_i - \sum_{j=i+1}^n u_{ij} x_j\right)$$

**Forward Substitution**

Solving Lc = b:

- Start with the first equation and solve for c1.
- Substitute into subsequent equations for c2, . . . , cn.

Formula:

$$c_i = b_i - \sum_{j=1}^{i-1} l_{ij} c_j$$

**Solving Ax = b Using LU**

Steps:

1. Factor A = LU.
2. Solve Lc = b using forward substitution.
3. Solve Ux = c using back substitution.

In [3]:
import numpy as np

def lu_decomposition(A):
    """
    Compute LU factorization without pivoting.
    Returns L and U such that A = L * U.
    """
    n = A.shape[0]
    L = np.eye(n)           # start with identity matrix for L
    U = A.copy().astype(float)  # make a copy of A for U

    for i in range(n):
        pivot = U[i, i]
        if pivot == 0:
            raise ValueError("Pivot is zero; row swapping (pivoting) needed.")

        for j in range(i+1, n):
            # factor to eliminate below the pivot
            factor = U[j, i] / pivot
            L[j, i] = factor            # store factor in L
            # subtract factor * pivot row from current row
            U[j, i:] = U[j, i:] - factor * U[i, i:]
    return L, U

def forward_substitution(L, b):
    """Solve Lc = b using forward substitution."""
    n = L.shape[0]
    c = np.zeros(n)
    for i in range(n):
        # compute c[i] using previously computed c[0:i]
        c[i] = b[i] - np.dot(L[i, :i], c[:i])
    return c

def back_substitution(U, c):
    """Solve Ux = c using back substitution."""
    n = U.shape[0]
    x = np.zeros(n)
    for i in reversed(range(n)):
        # compute x[i] from right to left using known x[i+1:]
        x[i] = (c[i] - np.dot(U[i, i+1:], x[i+1:])) / U[i, i]
    return x

# ---- main program ----
n = int(input("Enter number of rows (n): "))
A = []
print("Enter matrix A row by row (numbers separated by space):")
for i in range(n):
    row = list(map(float, input(f"Row {i+1}: ").split()))
    A.append(row)
A = np.array(A)

b = np.array(list(map(float, input("Enter vector b (numbers separated by space): ").split())))

# compute LU
L, U = lu_decomposition(A)

# solve step by step
c = forward_substitution(L, b)
x = back_substitution(U, c)

print("\nMatrix L:")
print(L)
print("\nMatrix U:")
print(U)
print("\nSolution vector x:")
print(x)


Enter number of rows (n): 3
Enter matrix A row by row (numbers separated by space):
Row 1: 2 1 1
Row 2: 4 5 2
Row 3: 2 -2 0
Enter vector b (numbers separated by space): 1 2 2

Matrix L:
[[ 1.  0.  0.]
 [ 2.  1.  0.]
 [ 1. -1.  1.]]

Matrix U:
[[ 2.  1.  1.]
 [ 0.  3.  0.]
 [ 0.  0. -1.]]

Solution vector x:
[ 1.  0. -1.]


**Definition:**

A regular matrix A can be factored as $A = LU$, where:
  - L: Lower triangular matrix with 1’s on the diagonal.
    The nonzero entries $l_{ij}$ in $L$ ($i > j$) correspond to the
    elementary row operations in Gaussian Elimination.
  - U: Upper triangular matrix (output of Gaussian Elimination).
  
    Purpose: Simplifies solving linear systems $Ax = b$ by reducing it to two triangular systems.